### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by hiroto0011** [Daviex/Steins-Gate-Archive-Compiler#2]
It's just work with nss.npa, cannot work with cg.npa, sound.npa,...

**Comment by Daviex** [comment]
Hey. Are you using it on USA Game?

**Comment by hiroto0011** [comment]
Of course

**Comment by Daviex** [comment]
Mmmh, I've to look at it so, because right now, I remember it worked perfectly for me when I uploaded it. 

When I've time I will try it and let you know! Maybe some edits I did to clean the code have corrupted some info at compression!

**Comment by hiroto0011** [comment]
So can I get your game version?

**Comment by Daviex** [comment]
The executable file say me that I've the 1.2.0.1. Hope it can help!

**Comment by hiroto0011** [comment]
Where do you get the game? I download it free in website

**Comment by hiroto0011** [comment]
Oh my... My version is 1.00, can I get your game?

**Comment by Daviex** [comment]
I can't remember where I get it... Try to search on torrents for JUST USA edition, it should be already this version...

**Comment by hiroto0011** [comment]
That's strange, all version of JAST Steins;Gate is 1.00e. I cannot find 1.2.0.1. That version is Jap ver.

**Comment by hiroto0011** [comment]
Wait, what's your locale? Japan?
