### ISSUE TITLE
CG

### ISSUE THREAD

**Issue by haku0011** [Daviex/Steins-Gate-Archive-Compiler#3]
How to work with CG folder, i try but it just makes a file cg.npa with 8 byte :(

**Comment by Daviex** [comment]
Did you moved the CG folder entirely over the executable?

**Comment by haku0011** [comment]
yeah, it's just work with a folder which don't have any folder inside!

**Comment by haku0011** [comment]
Folder CG has this folder
![1](https://cloud.githubusercontent.com/assets/16457725/12018631/adeb7ce8-ada8-11e5-9e16-b6ce6e10ec7f.png)
After that, drag it into executable
![2](https://cloud.githubusercontent.com/assets/16457725/12018632/adef5ed0-ada8-11e5-915d-2300b9e8a574.png)
It just say this
![3](https://cloud.githubusercontent.com/assets/16457725/12018633/adf00b64-ada8-11e5-88dd-d1d2f08779c7.png)
And it create this file :(
![4](https://cloud.githubusercontent.com/assets/16457725/12018634/adf11982-ada8-11e5-988c-28cf4615a5c3.png)

**Comment by Daviex** [comment]
Mmmh, ok, give me the time to reinstall Visual Studio, that I just formatted, and I will look into this and let you know, probably I broke the code while refactoring :)

**Comment by haku0011** [comment]
Tks! :)

**Comment by haku0011** [comment]
One more question, do you know where the text of the phone?

**Comment by Daviex** [comment]
Yep, I already did the tools, but I still need to works on them, in this period I couldn't do nothing. I need to optimize them and make a tutorial how to customize the executable.

**Comment by haku0011** [comment]
i am waiting for this :) do you know where the text of the Rintarou's phone?

**Comment by Daviex** [comment]
All the things about Phone are into the Executable of Steins Gate, that has pointer to every word that it use, but are not normal pointer, but physical pointer into memory already loaded, so you need to translate them to know where is the text. I already did all of that, with help of Krofna, that found out the real position of one of the word, from there I wrote all the code to translate it ^^

**Comment by haku0011** [comment]
this is so hard :( do you have any idea about it? how to translate it easier? :(

**Comment by Daviex** [comment]
Fixed.

It was a problem of new vesion of C#, that now requires a parameter to say that he needs to search for all files in every subdirectory into a directory.

Anyway, relax man, trust me, I already did everything to work over the phone things :+1:

**Comment by haku0011** [comment]
Tks :)

**Comment by haku0011** [comment]
New tools working very good with CGs, but now I don't know how to trans the phone :(

**Comment by haku0011** [comment]
I found nipa2 tools, it has phone. But it just works with japanese version patched eng. Do you have tools, Daviex?

**Comment by Daviex** [comment]
Man, I already answered you. I've everything, just wait.
